DROP TABLE IF EXISTS typ_zkousky;
DROP TABLE IF EXISTS otazky;
DROP TABLE IF EXISTS hodnoceni;
DROP TABLE IF EXISTS uzivatele;

CREATE TABLE typ_zkousky (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazev TEXT NOT NULL,
pocet_otazek TEXT NOT NULL,
cas TEXT NOT NULL
);

CREATE TABLE otazky (
id INTEGER PRIMARY KEY AUTOINCREMENT,
otazka_id INTEGER NOT NULL,
pravda TEXT NOT NULL,
nepravda_1 TEXT NOT NULL,
nepravda_2 TEXT NOT NULL,
FOREIGN KEY (otazka_id) REFERENCES typ_zkousky (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE hodnoceni(
id INTEGER PRIMARY KEY AUTOINCREMENT,
jmeno_id INTEGER NOT NULL,
jmeno TEXT NOT NULL,
typ_testu TEXT NOT NULL,
vysledek_testu TEXT NOT NULL,
cas TEXT NOT NULL,
FOREIGN KEY (jmeno_id) REFERENCES uzivatele (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE uzivatele (
id INTEGER PRIMARY KEY AUTOINCREMENT,
jmeno TEXT NOT NULL,
email TEXT NOT NULL,
heslo TEXT NOT NULL
);

--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

-- flask --app testy init-db     NOTE inicializace databáze